package org.apache.eventmesh.protocol.kafka.wire.message;

/**
 * Kafka API keys
 */
public class KafkaApiKeys {
    public static final short PRODUCE = 0;
    public static final short FETCH = 1;
    public static final short LIST_OFFSETS = 2;
    public static final short METADATA = 3;
    public static final short LEADER_AND_ISR = 4;
    public static final short STOP_REPLICA = 5;
    public static final short UPDATE_METADATA = 6;
    public static final short CONTROLLED_SHUTDOWN = 7;
    public static final short OFFSET_COMMIT = 8;
    public static final short OFFSET_FETCH = 9;
    public static final short FIND_COORDINATOR = 10;
    public static final short JOIN_GROUP = 11;
    public static final short HEARTBEAT = 12;
    public static final short LEAVE_GROUP = 13;
    public static final short SYNC_GROUP = 14;
    public static final short DESCRIBE_GROUPS = 15;
    public static final short LIST_GROUPS = 16;
    public static final short SASL_HANDSHAKE = 17;
    public static final short API_VERSIONS = 18;
    public static final short CREATE_TOPICS = 19;
    public static final short DELETE_TOPICS = 20;
    public static final short DELETE_RECORDS = 21;
    public static final short INIT_PRODUCER_ID = 22;
    public static final short OFFSET_FOR_LEADER_EPOCH = 23;
    public static final short ADD_PARTITIONS_TO_TXN = 24;
    public static final short ADD_OFFSETS_TO_TXN = 25;
    public static final short END_TXN = 26;
    public static final short WRITE_TXN_MARKERS = 27;
    public static final short TXN_OFFSET_COMMIT = 28;
    public static final short DESCRIBE_ACLS = 29;
    public static final short CREATE_ACLS = 30;
    public static final short DELETE_ACLS = 31;
    public static final short DESCRIBE_CONFIGS = 32;
    public static final short ALTER_CONFIGS = 33;
    public static final short ALTER_REPLICA_LOG_DIRS = 34;
    public static final short DESCRIBE_LOG_DIRS = 35;
    public static final short SASL_AUTHENTICATE = 36;
    public static final short CREATE_PARTITIONS = 37;
    public static final short CREATE_DELEGATION_TOKEN = 38;
    public static final short RENEW_DELEGATION_TOKEN = 39;
    public static final short EXPIRE_DELEGATION_TOKEN = 40;
    public static final short DESCRIBE_DELEGATION_TOKEN = 41;
    public static final short DELETE_GROUPS = 42;
    public static final short ELECT_LEADERS = 43;
    public static final short INCREMENTAL_ALTER_CONFIGS = 44;
    public static final short ALTER_PARTITION_REASSIGNMENTS = 45;
    public static final short LIST_PARTITION_REASSIGNMENTS = 46;
    public static final short OFFSET_DELETE = 47;
    public static final short DESCRIBE_CLIENT_QUOTAS = 48;
    public static final short ALTER_CLIENT_QUOTAS = 49;
    public static final short DESCRIBE_USER_SCRAM_CREDENTIALS = 50;
    public static final short ALTER_USER_SCRAM_CREDENTIALS = 51;
    public static final short VOTE = 52;
    public static final short BEGIN_QUORUM_EPOCH = 53;
    public static final short END_QUORUM_EPOCH = 54;
    public static final short DESCRIBE_QUORUM = 55;
    public static final short ALTER_PARTITION = 56;
    public static final short UPDATE_FEATURES = 57;
    public static final short ENVELOPE = 58;
    public static final short FETCH_SNAPSHOT = 59;
    public static final short DESCRIBE_CLUSTER = 60;
    public static final short DESCRIBE_PRODUCERS = 61;
    public static final short BROKER_REGISTRATION = 62;
    public static final short BROKER_HEARTBEAT = 63;
    public static final short UNREGISTER_BROKER = 64;
    public static final short DESCRIBE_TRANSACTIONS = 65;
    public static final short LIST_TRANSACTIONS = 66;
    public static final short ALLOCATE_PRODUCER_IDS = 67;
    public static final short CONSUMER_GROUP_HEARTBEAT = 68;
    public static final short CONSUMER_GROUP_DESCRIBE = 69;
    public static final short CONSUMER_GROUP_DELETE = 70;
    public static final short CONSUMER_GROUP_OFFSET_COMMIT = 71;
    public static final short CONSUMER_GROUP_OFFSET_FETCH = 72;
    public static final short CONSUMER_GROUP_OFFSET_DELETE = 73;
    public static final short CONSUMER_GROUP_MEMBER_DESCRIBE = 74;
    public static final short CONSUMER_GROUP_MEMBER_LEAVE = 75;
    public static final short CONSUMER_GROUP_MEMBER_ASSIGN = 76;
    public static final short CONSUMER_GROUP_MEMBER_SYNC = 77;
    public static final short CONSUMER_GROUP_MEMBER_JOIN = 78;
    public static final short CONSUMER_GROUP_MEMBER_HEARTBEAT = 79;
    public static final short CONSUMER_GROUP_MEMBER_LEAVE_GROUP = 80;
    public static final short CONSUMER_GROUP_MEMBER_SYNC_GROUP = 81;
    public static final short CONSUMER_GROUP_MEMBER_JOIN_GROUP = 82;
    public static final short CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP = 83;
    public static final short CONSUMER_GROUP_MEMBER_LEAVE_GROUP_GROUP = 84;
    public static final short CONSUMER_GROUP_MEMBER_SYNC_GROUP_GROUP = 85;
    public static final short CONSUMER_GROUP_MEMBER_JOIN_GROUP_GROUP = 86;
    public static final short CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP_GROUP = 87;
    public static final short CONSUMER_GROUP_MEMBER_LEAVE_GROUP_GROUP_GROUP = 88;
    public static final short CONSUMER_GROUP_MEMBER_SYNC_GROUP_GROUP_GROUP = 89;
    public static final short CONSUMER_GROUP_MEMBER_JOIN_GROUP_GROUP_GROUP = 90;
    public static final short CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP_GROUP_GROUP = 91;
    public static final short CONSUMER_GROUP_MEMBER_LEAVE_GROUP_GROUP_GROUP_GROUP = 92;
    public static final short CONSUMER_GROUP_MEMBER_SYNC_GROUP_GROUP_GROUP_GROUP = 93;
    public static final short CONSUMER_GROUP_MEMBER_JOIN_GROUP_GROUP_GROUP_GROUP = 94;
    public static final short CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP_GROUP_GROUP_GROUP = 95;
    public static final short CONSUMER_GROUP_MEMBER_LEAVE_GROUP_GROUP_GROUP_GROUP_GROUP = 96;
    public static final short CONSUMER_GROUP_MEMBER_SYNC_GROUP_GROUP_GROUP_GROUP_GROUP = 97;
    public static final short CONSUMER_GROUP_MEMBER_JOIN_GROUP_GROUP_GROUP_GROUP_GROUP = 98;
    public static final short CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP_GROUP_GROUP_GROUP_GROUP = 99;

    /**
     * Get API key name by number
     */
    public static String getApiKey(short apiKey) {
        switch (apiKey) {
            case PRODUCE: return "PRODUCE";
            case FETCH: return "FETCH";
            case LIST_OFFSETS: return "LIST_OFFSETS";
            case METADATA: return "METADATA";
            case LEADER_AND_ISR: return "LEADER_AND_ISR";
            case STOP_REPLICA: return "STOP_REPLICA";
            case UPDATE_METADATA: return "UPDATE_METADATA";
            case CONTROLLED_SHUTDOWN: return "CONTROLLED_SHUTDOWN";
            case OFFSET_COMMIT: return "OFFSET_COMMIT";
            case OFFSET_FETCH: return "OFFSET_FETCH";
            case FIND_COORDINATOR: return "FIND_COORDINATOR";
            case JOIN_GROUP: return "JOIN_GROUP";
            case HEARTBEAT: return "HEARTBEAT";
            case LEAVE_GROUP: return "LEAVE_GROUP";
            case SYNC_GROUP: return "SYNC_GROUP";
            case DESCRIBE_GROUPS: return "DESCRIBE_GROUPS";
            case LIST_GROUPS: return "LIST_GROUPS";
            case SASL_HANDSHAKE: return "SASL_HANDSHAKE";
            case API_VERSIONS: return "API_VERSIONS";
            case CREATE_TOPICS: return "CREATE_TOPICS";
            case DELETE_TOPICS: return "DELETE_TOPICS";
            case DELETE_RECORDS: return "DELETE_RECORDS";
            case INIT_PRODUCER_ID: return "INIT_PRODUCER_ID";
            case OFFSET_FOR_LEADER_EPOCH: return "OFFSET_FOR_LEADER_EPOCH";
            case ADD_PARTITIONS_TO_TXN: return "ADD_PARTITIONS_TO_TXN";
            case ADD_OFFSETS_TO_TXN: return "ADD_OFFSETS_TO_TXN";
            case END_TXN: return "END_TXN";
            case WRITE_TXN_MARKERS: return "WRITE_TXN_MARKERS";
            case TXN_OFFSET_COMMIT: return "TXN_OFFSET_COMMIT";
            case DESCRIBE_ACLS: return "DESCRIBE_ACLS";
            case CREATE_ACLS: return "CREATE_ACLS";
            case DELETE_ACLS: return "DELETE_ACLS";
            case DESCRIBE_CONFIGS: return "DESCRIBE_CONFIGS";
            case ALTER_CONFIGS: return "ALTER_CONFIGS";
            case ALTER_REPLICA_LOG_DIRS: return "ALTER_REPLICA_LOG_DIRS";
            case DESCRIBE_LOG_DIRS: return "DESCRIBE_LOG_DIRS";
            case SASL_AUTHENTICATE: return "SASL_AUTHENTICATE";
            case CREATE_PARTITIONS: return "CREATE_PARTITIONS";
            case CREATE_DELEGATION_TOKEN: return "CREATE_DELEGATION_TOKEN";
            case RENEW_DELEGATION_TOKEN: return "RENEW_DELEGATION_TOKEN";
            case EXPIRE_DELEGATION_TOKEN: return "EXPIRE_DELEGATION_TOKEN";
            case DESCRIBE_DELEGATION_TOKEN: return "DESCRIBE_DELEGATION_TOKEN";
            case DELETE_GROUPS: return "DELETE_GROUPS";
            case ELECT_LEADERS: return "ELECT_LEADERS";
            case INCREMENTAL_ALTER_CONFIGS: return "INCREMENTAL_ALTER_CONFIGS";
            case ALTER_PARTITION_REASSIGNMENTS: return "ALTER_PARTITION_REASSIGNMENTS";
            case LIST_PARTITION_REASSIGNMENTS: return "LIST_PARTITION_REASSIGNMENTS";
            case OFFSET_DELETE: return "OFFSET_DELETE";
            case DESCRIBE_CLIENT_QUOTAS: return "DESCRIBE_CLIENT_QUOTAS";
            case ALTER_CLIENT_QUOTAS: return "ALTER_CLIENT_QUOTAS";
            case DESCRIBE_USER_SCRAM_CREDENTIALS: return "DESCRIBE_USER_SCRAM_CREDENTIALS";
            case ALTER_USER_SCRAM_CREDENTIALS: return "ALTER_USER_SCRAM_CREDENTIALS";
            case VOTE: return "VOTE";
            case BEGIN_QUORUM_EPOCH: return "BEGIN_QUORUM_EPOCH";
            case END_QUORUM_EPOCH: return "END_QUORUM_EPOCH";
            case DESCRIBE_QUORUM: return "DESCRIBE_QUORUM";
            case ALTER_PARTITION: return "ALTER_PARTITION";
            case UPDATE_FEATURES: return "UPDATE_FEATURES";
            case ENVELOPE: return "ENVELOPE";
            case FETCH_SNAPSHOT: return "FETCH_SNAPSHOT";
            case DESCRIBE_CLUSTER: return "DESCRIBE_CLUSTER";
            case DESCRIBE_PRODUCERS: return "DESCRIBE_PRODUCERS";
            case BROKER_REGISTRATION: return "BROKER_REGISTRATION";
            case BROKER_HEARTBEAT: return "BROKER_HEARTBEAT";
            case UNREGISTER_BROKER: return "UNREGISTER_BROKER";
            case DESCRIBE_TRANSACTIONS: return "DESCRIBE_TRANSACTIONS";
            case LIST_TRANSACTIONS: return "LIST_TRANSACTIONS";
            case ALLOCATE_PRODUCER_IDS: return "ALLOCATE_PRODUCER_IDS";
            case CONSUMER_GROUP_HEARTBEAT: return "CONSUMER_GROUP_HEARTBEAT";
            case CONSUMER_GROUP_DESCRIBE: return "CONSUMER_GROUP_DESCRIBE";
            case CONSUMER_GROUP_DELETE: return "CONSUMER_GROUP_DELETE";
            case CONSUMER_GROUP_OFFSET_COMMIT: return "CONSUMER_GROUP_OFFSET_COMMIT";
            case CONSUMER_GROUP_OFFSET_FETCH: return "CONSUMER_GROUP_OFFSET_FETCH";
            case CONSUMER_GROUP_OFFSET_DELETE: return "CONSUMER_GROUP_OFFSET_DELETE";
            case CONSUMER_GROUP_MEMBER_DESCRIBE: return "CONSUMER_GROUP_MEMBER_DESCRIBE";
            case CONSUMER_GROUP_MEMBER_LEAVE: return "CONSUMER_GROUP_MEMBER_LEAVE";
            case CONSUMER_GROUP_MEMBER_ASSIGN: return "CONSUMER_GROUP_MEMBER_ASSIGN";
            case CONSUMER_GROUP_MEMBER_SYNC: return "CONSUMER_GROUP_MEMBER_SYNC";
            case CONSUMER_GROUP_MEMBER_JOIN: return "CONSUMER_GROUP_MEMBER_JOIN";
            case CONSUMER_GROUP_MEMBER_HEARTBEAT: return "CONSUMER_GROUP_MEMBER_HEARTBEAT";
            case CONSUMER_GROUP_MEMBER_LEAVE_GROUP: return "CONSUMER_GROUP_MEMBER_LEAVE_GROUP";
            case CONSUMER_GROUP_MEMBER_SYNC_GROUP: return "CONSUMER_GROUP_MEMBER_SYNC_GROUP";
            case CONSUMER_GROUP_MEMBER_JOIN_GROUP: return "CONSUMER_GROUP_MEMBER_JOIN_GROUP";
            case CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP: return "CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP";
            case CONSUMER_GROUP_MEMBER_LEAVE_GROUP_GROUP: return "CONSUMER_GROUP_MEMBER_LEAVE_GROUP_GROUP";
            case CONSUMER_GROUP_MEMBER_SYNC_GROUP_GROUP: return "CONSUMER_GROUP_MEMBER_SYNC_GROUP_GROUP";
            case CONSUMER_GROUP_MEMBER_JOIN_GROUP_GROUP: return "CONSUMER_GROUP_MEMBER_JOIN_GROUP_GROUP";
            case CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP_GROUP: return "CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP_GROUP";
            case CONSUMER_GROUP_MEMBER_LEAVE_GROUP_GROUP_GROUP: return "CONSUMER_GROUP_MEMBER_LEAVE_GROUP_GROUP_GROUP";
            case CONSUMER_GROUP_MEMBER_SYNC_GROUP_GROUP_GROUP: return "CONSUMER_GROUP_MEMBER_SYNC_GROUP_GROUP_GROUP";
            case CONSUMER_GROUP_MEMBER_JOIN_GROUP_GROUP_GROUP: return "CONSUMER_GROUP_MEMBER_JOIN_GROUP_GROUP_GROUP";
            case CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP_GROUP_GROUP: return "CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP_GROUP_GROUP";
            case CONSUMER_GROUP_MEMBER_LEAVE_GROUP_GROUP_GROUP_GROUP: return "CONSUMER_GROUP_MEMBER_LEAVE_GROUP_GROUP_GROUP_GROUP";
            case CONSUMER_GROUP_MEMBER_SYNC_GROUP_GROUP_GROUP_GROUP: return "CONSUMER_GROUP_MEMBER_SYNC_GROUP_GROUP_GROUP_GROUP";
            case CONSUMER_GROUP_MEMBER_JOIN_GROUP_GROUP_GROUP_GROUP: return "CONSUMER_GROUP_MEMBER_JOIN_GROUP_GROUP_GROUP_GROUP";
            case CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP_GROUP_GROUP_GROUP: return "CONSUMER_GROUP_MEMBER_HEARTBEAT_GROUP_GROUP_GROUP_GROUP";
            default: return "UNKNOWN(" + apiKey + ")";
        }
    }
}
